import { useState, useRef } from 'react';
let _setNotif=null;
export function NotifyProvider(){const [msg,setMsg]=useState('');const [show,setShow]=useState(false);const t=useRef(null);_setNotif=(m)=>{setMsg(m);setShow(true);clearTimeout(t.current);t.current=setTimeout(()=>setShow(false),2800);};return <div style={{position:'fixed',bottom:24,right:24,background:'#534AB7',color:'#fff',padding:'10px 18px',borderRadius:10,fontSize:12,fontWeight:500,zIndex:9999,opacity:show?1:0,transition:'opacity .3s',pointerEvents:'none',boxShadow:'0 4px 20px rgba(83,74,183,.4)'}}>{msg}</div>;}
export function notify(msg){if(_setNotif)_setNotif(msg);}
const bS={base:{padding:'5px 10px',fontSize:11,borderRadius:6,border:'1px solid #d0cfc8',background:'#fff',color:'#1a1915',cursor:'pointer',fontWeight:500},p:{background:'#534AB7',color:'#fff',borderColor:'#534AB7'},d:{background:'#FCEBEB',color:'#A32D2D',borderColor:'#F09595'},s:{background:'#EAF3DE',color:'#27500A',borderColor:'#97C459'},i:{background:'#E6F1FB',color:'#0C447C',borderColor:'#85B7EB'},w:{background:'#FAEEDA',color:'#633806',borderColor:'#FAC775'},bk:{background:'#EEEDFE',color:'#3C3489',borderColor:'#AFA9EC'}};
export function Btn({children,variant='base',onClick,disabled,style={}}){return <button onClick={onClick} disabled={disabled} style={{...bS.base,...(bS[variant]||{}),opacity:disabled?.5:1,...style}}>{children}</button>;}
const bC={'Pending':{bg:'#FAEEDA',color:'#633806'},'Delivered':{bg:'#EAF3DE',color:'#27500A'},active:{bg:'#EAF3DE',color:'#27500A'},inactive:{bg:'#F1EFE8',color:'#5F5E5A'},Cash:{bg:'#EAF3DE',color:'#27500A'},'Bank transfer':{bg:'#E6F1FB',color:'#0C447C'},pending:{bg:'#FAEEDA',color:'#633806'},delivered:{bg:'#EAF3DE',color:'#27500A'},closed:{bg:'#F1EFE8',color:'#5F5E5A'},booking:{bg:'#E6F1FB',color:'#0C447C'},'Stock in':{bg:'#EAF3DE',color:'#27500A'},Transfer:{bg:'#E6F1FB',color:'#0C447C'},'Stock out':{bg:'#FAEEDA',color:'#633806'},Deposit:{bg:'#EEEDFE',color:'#3C3489'},Receipt:{bg:'#FAEEDA',color:'#633806'},'Branch manager':{bg:'#EEEDFE',color:'#3C3489'},'Stock manager':{bg:'#E1F5EE',color:'#085041'}};
export function Badge({label}){const c=bC[label]||{bg:'#F1EFE8',color:'#5F5E5A'};return <span style={{display:'inline-block',padding:'2px 8px',borderRadius:20,fontSize:10,fontWeight:500,background:c.bg,color:c.color}}>{label}</span>;}
export function Modal({open,onClose,title,children,width=400}){if(!open)return null;return <div onClick={onClose} style={{position:'fixed',inset:0,background:'rgba(0,0,0,.4)',zIndex:50,display:'flex',alignItems:'center',justifyContent:'center'}}><div onClick={e=>e.stopPropagation()} style={{background:'#fff',borderRadius:12,padding:20,width,maxWidth:'95vw',border:'1px solid #d0cfc8',maxHeight:'90vh',overflowY:'auto',boxShadow:'0 20px 60px rgba(0,0,0,.15)'}}>{title&&<h3 style={{fontSize:14,fontWeight:600,marginBottom:15,color:'#1a1915'}}>{title}</h3>}{children}</div></div>;}
export function Field({label,children}){return <div style={{marginBottom:10}}><label style={{display:'block',fontSize:11,color:'#706f6b',marginBottom:3,fontWeight:500}}>{label}</label>{children}</div>;}
export const inputStyle={width:'100%',padding:'7px 10px',fontSize:12,border:'1px solid #d0cfc8',borderRadius:7,background:'#fff',color:'#1a1915',boxSizing:'border-box'};
export function Input({value,onChange,type='text',placeholder,readonly,style={}}){return <input type={type} value={value||''} onChange={onChange} placeholder={placeholder} readOnly={readonly} style={{...inputStyle,...(readonly?{background:'#f7f7f5'}:{}),...style}}/>;}
export function Select({value,onChange,options,style={}}){return <select value={value||''} onChange={onChange} style={{...inputStyle,...style}}>{options.map(o=>typeof o==='string'?<option key={o} value={o}>{o}</option>:<option key={o.value} value={o.value}>{o.label}</option>)}</select>;}
export function Textarea({value,onChange,placeholder}){return <textarea value={value||''} onChange={onChange} placeholder={placeholder} style={{...inputStyle,minHeight:54,resize:'vertical'}}/>;}
export function Grid2({children}){return <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}>{children}</div>;}
export function ModalActions({onCancel,onSave,saveLabel='Save',loading}){return <div style={{display:'flex',gap:8,justifyContent:'flex-end',marginTop:16}}><Btn onClick={onCancel}>Cancel</Btn><Btn variant="p" onClick={onSave} disabled={loading}>{loading?'Saving...':saveLabel}</Btn></div>;}
export function Stats({items}){return <div style={{display:'grid',gridTemplateColumns:`repeat(${items.length},minmax(0,1fr))`,gap:10,marginBottom:14}}>{items.map(({label,value,color})=><div key={label} style={{background:'#fff',border:'1px solid #e3e2dc',borderRadius:8,padding:13}}><div style={{fontSize:20,fontWeight:600,color:color||'#1a1915'}}>{value}</div><div style={{fontSize:10,color:'#706f6b',textTransform:'uppercase',letterSpacing:'0.04em',marginTop:2}}>{label}</div></div>)}</div>;}
export function FilterBar({children}){return <div style={{display:'flex',gap:6,alignItems:'center',flexWrap:'wrap',marginBottom:12}}>{children}</div>;}
const fI={fontSize:11,padding:'5px 8px',border:'1px solid #d0cfc8',borderRadius:6,background:'#fff',color:'#1a1915'};
export function FInput({value,onChange,placeholder,type='text'}){return <input type={type} value={value||''} onChange={e=>onChange(e.target.value)} placeholder={placeholder} style={fI}/>;}
export function FSelect({value,onChange,options}){return <select value={value||''} onChange={e=>onChange(e.target.value)} style={fI}>{options.map(o=>typeof o==='string'?<option key={o} value={o}>{o}</option>:<option key={o.value} value={o.value}>{o.label}</option>)}</select>;}
export function FSep(){return <span style={{fontSize:11,color:'#706f6b'}}>to</span>;}
export function Table({cols,rows,empty='No data found'}){return <div style={{background:'#fff',border:'1px solid #e3e2dc',borderRadius:10,overflow:'hidden',marginBottom:12}}><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:12,whiteSpace:'nowrap'}}><thead><tr>{cols.map(c=><th key={c} style={{padding:'8px 11px',textAlign:'left',fontSize:10,fontWeight:600,color:'#706f6b',background:'#f7f7f5',borderBottom:'1px solid #e3e2dc',textTransform:'uppercase',letterSpacing:'0.04em'}}>{c}</th>)}</tr></thead><tbody>{rows.length?rows:<tr><td colSpan={cols.length} style={{textAlign:'center',padding:24,color:'#a8a79f'}}>{empty}</td></tr>}</tbody></table></div></div>;}
export function TR({children,highlight}){return <tr style={{background:highlight?'rgba(83,74,183,.04)':undefined}} onMouseEnter={e=>e.currentTarget.style.background='#f7f7f5'} onMouseLeave={e=>e.currentTarget.style.background=highlight?'rgba(83,74,183,.04)':''}>{children}</tr>;}
export function TD({children,style={}}){return <td style={{padding:'8px 11px',borderBottom:'1px solid #e3e2dc',color:'#1a1915',verticalAlign:'middle',...style}}>{children}</td>;}
export function SectionHeader({left,right}){return <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:12}}><div>{left}</div><div style={{display:'flex',gap:7}}>{right}</div></div>;}
export function Loading(){return <div style={{textAlign:'center',padding:40,color:'#706f6b',fontSize:13}}>Loading...</div>;}
export function exportCSV(filename,rows){const csv=rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href='data:text/csv,'+encodeURIComponent(csv);a.download=filename+'_'+new Date().toISOString().split('T')[0]+'.csv';a.click();}
export function Tabs({tabs,active,onChange}){return <div style={{display:'flex',gap:3,background:'#f7f7f5',padding:3,borderRadius:8,width:'fit-content',marginBottom:12}}>{tabs.map(t=><button key={t} onClick={()=>onChange(t)} style={{padding:'4px 13px',fontSize:11,borderRadius:5,cursor:'pointer',color:active===t?'#1a1915':'#706f6b',border:active===t?'1px solid #e3e2dc':'none',background:active===t?'#fff':'none',fontWeight:active===t?500:400}}>{t}</button>)}</div>;}
